name: cicd
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [dev, master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@v3
      # 생략
  image-build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - name: checkout the code
      uses: actions/checkout@v3
      # 생략
  deploy:
    runs-on: ubuntu-latest
    needs: [ image-build ]
    steps:
    - name: checkout the code
      uses: actions/checkout@v3
      # 생략