apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app-{{ .Values.environment }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
