apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: my-app-{{ .Values.environment }}
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
