name: Concurrency 2
on: push

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run a script
      run: |
        sleep 300
