name: issue-level-notify

on:
  issues:
    types: [opened]

jobs:
  get-keyword:
    runs-on: ubuntu-latest
    outputs:
      level: ${{ steps.get-keyword.outputs.level }}
    steps:
    - name: use checkout action
      uses: actions/checkout@v4
    - name: get keyword
      id: get-keyword
      run: |
        echo '${{ toJSON(github.event.issue) }}' 
        echo ${{ github.event.issue.html_url }}
        echo level=Undefined >> $GITHUB_OUTPUT

        keywords=$(cat keyword-list.txt)
        for keyword in $keywords; do
          if [[ "${{ github.event.issue.title }}" =~ "$keyword" ]]; then
            echo level=$keyword >> $GITHUB_OUTPUT
          fi
        done


  slack:
    needs: [get-keyword]
    if: needs.get-keyword.outputs.level != 'Undefined'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["${{ needs.get-keyword.outputs.level }}"]
    environment: ${{ matrix.environment }}
    steps:
    - name: slack 
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "attachments": [
              {
                "pretext": "issue alert message",
                "color": "28a745",
                "fields": [
                  {
                    "title": "Level : ${{ needs.get-keyword.outputs.level }}",
                    "short": true,
                    "value": "issue url : ${{ github.event.issue.html_url }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK