 name: issue-keyword-notify

on:
  issues:
    types: [opened]

jobs:
  get-keyword:
    runs-on: ubuntu-latest
    if: |
      job level에서 contains사용 
    outputs:
      keyword: ${{ steps.issue-title.outputs.keyword }}
    steps:
    - name: create output
      id: issue-title
      run: |
        # 키워드가 critical -> output: critical
        # 키워드가 normal -> output: normal

  slack:
    needs: [get-keyword]
    runs-on: ubuntu-latest
    environment: keyword
    steps:
    - name: slack 
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          # 생략
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK