name: create-repo
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'set repo prefix'
        required: true
        default: 'service'
        type: choice
        options:
        - example
        - service
      name:
        description: 'set repo name'
        required: true
        default: 'github-actions'
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
    - name: gh auth login
      run: |
        echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
    - name: create-repo
      id: create-repo
      run: |
        gh repo create sangwon-action/${{ inputs.prefix }}-${{ inputs.name }} --public --add-readme
    - name: slack 
      if: keyword == 'critical'
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          # 생략 
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.CRITICAL_SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    - name: slack 
      if: keyword == 'normal'
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          # 생략
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.NORMAL_SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    - name: slack 
      if: keyword == 'low'
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          # 생략
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.LOW_SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    - name: slack 
      if: keyword == 'high'
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          # 생략
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.HIGH_SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK