name: matrix
on: workflow_dispatch

jobs:
  test-python-3-7:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - name: run python
      run: python script.py
  
  test-python-3-8:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: run python
      run: python script.py
  
  test-python-3-9:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: run python
      run: python script.py



