name: env level
on: workflow_dispatch


jobs:
  get-env:
    runs-on: ubuntu-latest
    steps:
    - name: create env
      run: |
        echo "level=job" >> $GITHUB_ENV
    - name: check env
      run: echo ${{ env.level }}